export const LOADING_MUTATION = "LOADING_MUTATION";
export const ERROR_MUTATION = "ERROR_MUTATION";
export const AUTHENTICATED_MUTATION = "AUTHENTICATED_MUTATION";
export const USER_MUTATION = "USER_MUTATION";
export const RESET_MUTATION = "RESET_MUTATION";
