export const LOADING_GETPRODUCT_MUTATION = "LOADING_GETPRODUCT_MUTATION";
export const ERROR_MUTATION = "ERROR_MUTATION";
export const PRODUCTLIST_MUTATION = "PRODUCTLIST_MUTATION";
export const PRODUCTQUANTITY_MUTATION = "PRODUCTQUANTITY_MUTATION";

export const ADD_TO_WISHLIST_MUTATION = "ADD_TO_WISHLIST_MUTATION";
export const WISHLIST_MUTATION = "WISHLIST_MUTATION";

export const LOADING_GETCATEGORY_MUTATION = "LOADING_GETCATEGORY_MUTATION";
export const CATEGORYLIST_MUTATION = "CATEGORYLIST_MUTATION";
export const CATEGORYQUANTITY_MUTATION = "CATEGORYQUANTITY_MUTATION";

export const LOADING_PRODUCTCREATE_MUTATION = "LOADING_PRODUCTCREATE_MUTATION";

export const LOADING_PRODUCTDELETE_MUTATION = "LOADING_PRODUCTDELETE_MUTATION";
export const REMOVE_FROM_PRODUCTLIST = "REMOVE_FROM_PRODUCTLIST";
